### ISSUE TITLE
cannot load such file -- capistrano/rbenv

### ISSUE THREAD

**Issue by alpracka** [capistrano/rbenv#8]
Hello,

I have similar problem as was mentioned here before, but the solution doesn't work in my case. (I'm using rbenv on both development and production server, and Rails 4)

In Gemfile:

``` ruby
# Use Capistrano for deployment
group :development do
  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
end
```

After `bundle install` in Gemfile.lock:

```
    capistrano (3.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 0.0.23)
    capistrano-platform-resources (0.1.2)
      capistrano
    capistrano-rails (1.0.0)
      capistrano
    capistrano-rbenv (1.0.3)
      capistrano
      capistrano-platform-resources (>= 0.1.0)
```

Then `cap install`

In Capfile:

``` ruby
require 'capistrano/rbenv'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
```

After `cap production deploy` or `bundle exec cap production deploy` I get this:

```
$ bundle exec cap production deploy --trace
cap aborted!
cannot load such file -- capistrano/rbenv
/Users/nikos/workspace/app/Capfile:19:in `require'
/Users/nikos/workspace/app/Capfile:19:in `<top (required)>'
/Users/nikos/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/rake_module.rb:25:in `load'
/Users/nikos/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/rake_module.rb:25:in `load_rakefile'
/Users/nikos/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:637:in `raw_load_rakefile'
/Users/nikos/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:94:in `block in load_rakefile'
/Users/nikos/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/nikos/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:93:in `load_rakefile'
/Users/nikos/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/capistrano-3.0.0/lib/capistrano/application.rb:22:in `load_rakefile'
/Users/nikos/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:77:in `block in run'
/Users/nikos/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/nikos/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/Users/nikos/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/capistrano-3.0.0/lib/capistrano/application.rb:12:in `run'
/Users/nikos/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/capistrano-3.0.0/bin/cap:3:in `<top (required)>'
/Users/nikos/.rbenv/versions/2.0.0-p247/bin/cap:23:in `load'
/Users/nikos/.rbenv/versions/2.0.0-p247/bin/cap:23:in `<main>'
```

Thanks for help.

**Comment by sooraj4u** [comment]
try this command
 #bundle exec cap install STAGES=production
